### ISSUE TITLE
Suspect code here rickle 

### ISSUE THREAD

**Issue by RobertCekay** [rleitch/QueueConnect#1]
![bears](https://github.com/rleitch/QueueConnect/assets/7673544/0098f401-7eeb-432c-bca0-d5afe33e1258)

**Comment by rleitch** [comment]
@RobertCekay dude, you're still alive? I assumed you had a mental breakdown and dropped off the face of the earth.

**Comment by RobertCekay** [comment]
I did have a mental breakdown but I remain on earth!
